name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Autorise cette action à écrire sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet à un seul déploiement de s'exécuter à la fois
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Convex Backend
        run: npx convex deploy
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}

      - name: Build Vite Frontend
        run: npm run build
        env:
          VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Dossier généré par le build Vite

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
